# Generated by Django 5.2.1 on 2025-05-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='ano',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='dono',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
    ]
