# Generated by Django 5.2.1 on 2025-05-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_remove_veiculo_ano_veiculo_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='dono',
            field=models.CharField(default='', max_length=100),
        ),
    ]
